### ISSUE TITLE
No env vars in pre/post tasks

### ISSUE THREAD

**Issue by molowny** [runabol/tork#248]
There is a problem with passing env variables to pre/post tasks:

with:
```toml
[middleware.task.hostenv]
vars = [
  "AWS_ACCESS_KEY_ID", 
  "AWS_SECRET_ACCESS_KEY"
]
```

variables are correctly forwarded to tasks, but not to pre/post:

example:

```yaml
tasks:
  - name: process
    run: aws s3 cp /tmp/master.mov s3://bucket/master.mov # will work
    image: amazon/aws-cli:latest
    post:
      - name: upload the final video to minio
        run: aws s3 cp /tmp/master.mov s3://bucket/master.mov # won't work (no AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY)
        image: amazon/aws-cli:latest
```
