### ISSUE TITLE
Pre/Post task evaluate issue when used with job middleware

### ISSUE THREAD

**Issue by v36372** [runabol/tork#296]
I'm currently having the following setup:

```go
func (c *Coordinator) ModifyInputMiddleware(next job.HandlerFunc) job.HandlerFunc {
	return func(ctx context.Context, et job.EventType, j *tork.Job) error {
		inputs := make(map[string]string)
		inputs["Hello"] = "World"
		newJob := j.Clone()
		newJob.Inputs = inputs
		newJob.Context.Inputs = inputs
		return next(ctx, et, newJob)
	}
}
...
coordinator.SetJobMiddleware(coordinator.ModifyInputMiddleware)
```

I have a job that makes use of each task and also pre task:

```yml
name: Hello world
inputs:
  Hello: Abc123
tasks:
  - name: For each
    each:
      list: "{{ ['1','2','3'] }}"
      task:
        name: Each
        run: echo $HELLO > $TORK_OUTPUT
        env:
          HELLO: "{{ inputs.Hello }}"     
        image: ubuntu:mantic
        pre:
          - name: Pre
            run: |
              echo $HELLO
            image: ubuntu:mantic
            env:
              HELLO: "{{ inputs.Hello }}"
        retry:
          limit: 1
```

This would produce `Hello: Abc123` not `Hello: World`. Any idea what I did wrong and how to fix it?
