### ISSUE TITLE
Custom Mounter for docker

### ISSUE THREAD

**Issue by markdessain** [runabol/tork#370]
I was looking at creating a custom mounter for a docker worker.

I already have a volume created with `docker volume`

```bash
docker volume ls
DRIVER    VOLUME NAME
local     abc_example_data
...
```

And I wanted to be able to attach that to a task:

```yaml
...
mounts:
    - type: my_custom_mount
      source: abc_example_data
      target: /abc/data
...
```

But I came across this bit of code which seems to check that the mounter type is either: `tork.MountTypeVolume`, `tork.MountTypeBind` or `tork.MountTypeTmpfs`. All other custom types will raise an error: `unknown mount type`.

https://github.com/runabol/tork/blob/4319d73113230a79fb110c49abf1c87ff0324b17/runtime/docker/docker.go#L180-L208

Am I correct in saying that this switch logic would need to be updated to allow custom mounts for docker workers?

Thanks for Tork btw 😃, I really like the way it is possible to extend each component.

**Comment by markdessain** [comment]
My work around for my current situation is to just use the bind and point to where docker volume has created the data on disk:

```yaml
    mounts:
      - type: bind
        source: /var/lib/docker/volumes/abc_example_data/_data
        target: /abc/data
```
