### ISSUE TITLE
Question: Example implementation of conditional branching

### ISSUE THREAD

**Issue by aflatoon2874** [runabol/tork#532]
I need help on implementing a workflow that has conditional branching. Is there an example implementation that can be shared?

Thanking you all. :)

**Comment by runabol** [comment]
Hey there. Check out https://www.tork.run/tasks

It has lots of examples, including including conditionals.

**Comment by aflatoon2874** [comment]
In case I have a workflow similar to the attached image. How can I write my tasks config to implement it.
![Image](https://github.com/user-attachments/assets/deda5fa8-2e38-4725-980d-47eae38bda94)

**Comment by runabol** [comment]
```yaml
name: my job
inputs:
  fruit: banana
  studioshare_api_url: https://api.studioshare.wds.io
tasks:
  - name: my first task
    run: echo hello world
    image: alpine:3.18.3

  - name: my apple task
    run: echo hello apple
    image: alpine:3.18.3
    if: "{{ inputs.fruit == 'apple'}}"

  - name: my banana task
    if: "{{ inputs.fruit == 'banana'}}"
    subjob:
      name: my sub job
      tasks:
        - name: my first sub task
          run: echo subtask 1
          image: alpine:3.18.3
        - name: my second sub task
          run: echo subtask 2
          image: alpine:3.18.3

  - name: my last task
    run: echo goodbye world
    image: alpine:3.18.3
```
